---
title: "Loan Data Exploration"
author: "Dr. Prashant Mishra"
date: "4/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(DBI)
library(RSQLite)
```

##Loading Data using SQLite
```{r}
url = "database.sqlite"
con = dbConnect(SQLite(), dbname=url)
myQuery <- dbSendQuery(con, "SELECT * FROM loan")
loan_data <- dbFetch(myQuery, n = -1)
dbClearResult(myQuery)
```

Original Data
```{r}
original_data = loan_data

```

##Structuring the Data
```{r}
library(tidyr)
library(zoo)
loan_data = as_tibble(original_data)
loan_data = loan_data[!is.na(loan_data$member_id),]

loan_data = loan_data %>% replace_na(list(emp_title="unknown",title="unknown",annual_inc=0,delinq_2yrs=median(loan_data$delinq_2yrs,na.rm = TRUE),inq_last_6mths=median(loan_data$inq_last_6mths,na.rm = TRUE),open_acc=median(loan_data$open_acc,na.rm = TRUE),pub_rec=median(loan_data$pub_rec,na.rm = TRUE),total_acc=median(loan_data$total_acc,na.rm = TRUE),collections_12_mths_ex_med=median(loan_data$collections_12_mths_ex_med,na.rm = TRUE),acc_now_delinq=median(loan_data$acc_now_delinq,na.rm = TRUE),tot_coll_amt=median(loan_data$tot_coll_amt,na.rm = TRUE)))

loan_data$earliest_cr_line = loan_data$earliest_cr_line %>% na.locf
loan_data$revol_util = loan_data$revol_util %>% na.locf
loan_data$last_credit_pull_d = loan_data$last_credit_pull_d %>% na.locf



loan_data$id = as.factor(loan_data$id)
loan_data$term = as.factor(loan_data$term)
loan_data$member_id = as.factor(loan_data$member_id)
loan_data$grade = as.factor(loan_data$grade)
loan_data$sub_grade = as.factor(loan_data$sub_grade)
loan_data$emp_length = as.factor(loan_data$emp_length)
loan_data$home_ownership = as.factor(loan_data$home_ownership)
loan_data$verification_status = as.factor(loan_data$verification_status)
loan_data$loan_status = as.factor(loan_data$loan_status)
loan_data$pymnt_plan = as.factor(loan_data$pymnt_plan)
loan_data$purpose = as.factor(loan_data$purpose)
loan_data$id = as.factor(loan_data$id)
loan_data$zip_code = as.factor(loan_data$zip_code)
loan_data$addr_state = as.factor(loan_data$addr_state)
loan_data$initial_list_status = as.factor(loan_data$initial_list_status)
loan_data$application_type = as.factor(loan_data$application_type)
loan_data$verification_status_joint = as.factor(loan_data$verification_status_joint)
loan_data$int_rate = as.numeric(gsub("%", "", loan_data$int_rate))
loan_data$revol_util = as.numeric(gsub("%", "", loan_data$revol_util))
loan_data$issue_d <- as.Date(gsub("^", "01-", loan_data$issue_d), format="%d-%b-%Y")
loan_data$earliest_cr_line <- as.Date(gsub("^", "01-", loan_data$earliest_cr_line), format="%d-%b-%Y")
loan_data$last_pymnt_d <- as.Date(gsub("^", "01-", loan_data$last_pymnt_d), format="%d-%b-%Y")
loan_data$next_pymnt_d <- as.Date(gsub("^", "01-", loan_data$next_pymnt_d), format="%d-%b-%Y")
loan_data$last_credit_pull_d <- as.Date(gsub("^", "01-", loan_data$last_credit_pull_d), format="%d-%b-%Y")
loan_data$next_pymnt_d <- as.Date(gsub("^", "01-", loan_data$next_pymnt_d), format="%d-%b-%Y")

str(loan_data)
summary(loan_data)
```




```{r}
library(gmodels)
CrossTable(loan_data$loan_status, loan_data$grade)
```


```{r}
library(ggplot2)
pl1 = ggplot(loan_data, aes(x = loan_status, fill = initial_list_status));
pl2 = pl1 + geom_bar()
pl2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
pl3 = pl1 + geom_bar(position = "fill") + ylab("proportion")
pl3+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}
pl1 = ggplot(loan_data, aes(x = loan_status, fill = loan_amnt));
pl2 = pl1 + geom_bar()+facet_grid(~initial_list_status)
pl2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
pl2 = pl1 + geom_bar(position = "fill") + ylab("proportion")+facet_grid(~initial_list_status)
pl2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
Desc(loan_data$loan_amnt, main = "Loan amount distribution", plotit = TRUE)
```





```{r}
amnt_grade <- loan_data %>% 
  select(issue_d, loan_amnt, grade) %>% 
  group_by(issue_d, grade) %>% 
  summarise(Amount = sum(loan_amnt))

p <- ggplot(amnt_grade,aes(x = issue_d, y = Amount))
p + geom_area(aes(fill=grade)) + xlab("Issue Date")
```

```{r}
amnt_status <- loan_data %>% 
  select(issue_d, loan_amnt, loan_status) %>% 
  group_by(issue_d, loan_status) %>% 
  summarise(Amount = sum(loan_amnt))

p <- ggplot(amnt_status,aes(x = issue_d, y = Amount))
p + geom_area(aes(fill=loan_status)) + xlab("Issue Date")
```

```{r}
library(tm)
library(RColorBrewer)
library(wordcloud)
library(tidyr)

df_title <- data.frame(doc_id = row.names(loan_data),text=loan_data$title)
loan_descriptions.corpus <- Corpus(DataframeSource(df_title))
loan_descriptions.corpus <- tm_map(loan_descriptions.corpus, removePunctuation)
loan_descriptions.corpus <- tm_map(loan_descriptions.corpus, content_transformer(tolower))

wordcloud(loan_descriptions.corpus,
          max.words = 100,
          random.order=FALSE, 
          rot.per=0.30, 
          use.r.layout=FALSE, 
          colors=brewer.pal(8, "Paired"))
```

```{r}
df_title2 <- data.frame(doc_id = row.names(loan_data),text=loan_data$emp_title)
loan_descriptions.corpus <- Corpus(DataframeSource(df_title2))
loan_descriptions.corpus <- tm_map(loan_descriptions.corpus, removePunctuation)
loan_descriptions.corpus <- tm_map(loan_descriptions.corpus, content_transformer(tolower))

wordcloud(loan_descriptions.corpus,
          max.words = 100,
          random.order=FALSE, 
          rot.per=0.30, 
          use.r.layout=FALSE, 
          colors=brewer.pal(8, "Paired"))
```

```{r}
df_title3 <- data.frame(doc_id = row.names(loan_data),text=loan_data$desc)
loan_descriptions.corpus <- Corpus(DataframeSource(df_title3))
loan_descriptions.corpus <- tm_map(loan_descriptions.corpus, removePunctuation)
loan_descriptions.corpus <- tm_map(loan_descriptions.corpus, content_transformer(tolower))

wordcloud(loan_descriptions.corpus,
          max.words = 100,
          random.order=FALSE, 
          rot.per=0.30, 
          use.r.layout=FALSE, 
          colors=brewer.pal(8, "Paired"))
```

```{r}
pl1 = ggplot(loan_data, aes(x = grade, y = int_rate, color=grade));
pl2 = pl1 + geom_boxplot()
pl2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
dti_grade <- loan_data %>% 
  select(dti, grade) %>% 
  filter(dti < 100)
pl1 = ggplot(dti_grade, aes(x = grade, y = dti, color=grade));
pl2 = pl1 + geom_boxplot()
pl2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
pl = ggplot(loan_data, aes(x = grade, y = annual_inc, color=grade));
pl3 = pl + geom_violin()
pl3 + theme(axis.text.x = element_text(angle = 90, hjust = 1))

inc_grade <- loan_data %>% 
  select(annual_inc, grade) %>% 
  filter(annual_inc < 250000)

pl1 = ggplot(inc_grade, aes(x = grade, y = annual_inc, color=grade));
pl2 = pl1 + geom_violin()
pl2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}
bad_indicators <- c("Charged Off ",
                    "Default",
                    "Does not meet the credit policy. Status:Charged Off",
                    "In Grace Period", 
                    "Default Receiver", 
                    "Late (16-30 days)",
                    "Late (31-120 days)")

# assign certain statuses to a 'bad' ('0') group
loan_data$is_bad <- ifelse(loan_data$loan_status %in% bad_indicators, 0,
                          ifelse(loan_data$loan_status=="", NA, 1)
                          )

```

```{r}
# figure out which columns are numeric so that we can look at the distribution
numeric_cols <- sapply(loan_data, is.numeric)

# turn the data into long format
library(reshape2)
loan_data.lng <- melt(loan_data[,numeric_cols], id="is_bad")

library(DT)

loan_data %>% 
  filter(is_bad == '0') %>% 
  select(annual_inc, int_rate, loan_status) %>% 
  datatable(., options = list(pageLength = 10))
```



```{r}
#lotofmissing <- c("mths_since_last_delinq","mths_since_last_record","next_pymnt_d","mths_since_last_major_derog","annual_inc_joint","dti_joint","verification_status_joint","tot_cur_bal","open_acc_6m","open_il_6m","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m")
#NonMissingLoad_data <- loan_data %>% select(-(tot_cur_bal:inq_last_12m),-mths_since_last_delinq,-mths_since_last_record,-last_pymnt_d,-next_pymnt_d,-mths_since_last_major_derog,-annual_inc_joint,-dti_joint,-verification_status_joint)

selectedLoad_data <- loan_data %>% select(loan_amnt,int_rate,installment,annual_inc,dti,total_pymnt,policy_code,is_bad)

# figure out which columns are numeric so that we can look at the distribution
numeric_cols <- sapply(selectedLoad_data, is.numeric)

# turn the data into long format
library(reshape2)
selectedLoad_data.lng <- melt(selectedLoad_data[,numeric_cols], id="is_bad")

# plot the distribution for 'bad' and 'good' for each numeric variable
p <- ggplot(aes(x = value, group = is_bad, colour = factor(is_bad)), 
            data = selectedLoad_data.lng)
# create the plot to check if there are any good variables that can be used in predictive models
p + geom_density() +
  facet_wrap(~variable, scales="free",ncol = 3) + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
```{r}

```































































































